lib/models/__tests__/base-locale.schema.js
lib/models/base-locale.js
lib/models/numero.js
lib/models/voie.js
lib/routes/__tests__/base-locale.js
lib/routes/__tests__/numeros.js
lib/routes/__tests__/voies.js
lib/routes/index.js
lib/util/payload.js
lib/util/payload.test.js

Actuellement une erreur de validation provoque une `erreur 500`.
Désormais l'API renvoi une `erreur 400` avec le détails des erreurs de validation sous la forme suivante:
```
{
code: 400,
message: 'Invalid payload',
validation: {
foo: ['err1', 'err2'],
bar: ['err']
}
}
```

Amélioration des erreurs de validation

---

lib/models/__tests__/numero.mongo.js
lib/util/__tests__/payload.js
lib/util/payload.js

- Plus de magic casting : le type attendu doit être respecté
- Joi permet déjà de filter les clés reconnues
L'implémentation précédente laisser passer les valeurs dont le type pouvait être casté, mais enregistrait la mauvaise version.

Modification du comportement de la validation

---

docker-compose.yml

So it doesn’t warn about SMTP settings.

Run api in development mode in docker-compose

---

lib/models/__tests__/numero.mongo.js
lib/models/numero.js
lib/routes/__tests__/numeros.js

Ce nouveau champs n'existe pas à la création d'un numéro mais peut être ajouté lors d'une modification.
Il peut être à `null` mais de peut dépasser 5000 caractères.

Ajoute les commentaires au schéma Numero

---

lib/models/__tests__/base-locale.mongo.js
lib/models/__tests__/base-locale.schema.js
lib/models/base-locale.js
lib/routes/__tests__/base-locale.js

Nouvelle propriété `status` qui peut avoir les valeurs suivantes:
- "draft"
- "ready-to-publish"
Par défaut cette propriété est équal à "draft" lors de la création d'une base locale. 
Fix #86

Ajout d'un statut au modèle base locale

---

lib/models/__tests__/base-locale.mongo.js
lib/models/__tests__/numero.mongo.js
lib/models/__tests__/voie.mongo.js
lib/util/__tests__/payload.js

Corrige le deuxième paramètre envoyé à `t.throws` et `t.throwsAsync`

Fix throws tests

---

lib/export/geojson.js
lib/models/__tests__/voie.mongo.js
lib/models/__tests__/voie.schema.js
lib/models/voie.js
lib/routes/__tests__/voies.js

L'ajout des champs `typeNumerotation` et `trace` au modèle `Voie` permettent la création de voies avec une numérotation métrique.

Ajout de typeNumerotation et trace au modèle Voie

---

.env.sample
lib/emails/bal-creation-notification.js

- `editeur.adresse.data.gouv.fr` devient `mes-adresses.data.gouv.fr`
- Ajout d'un lien visible vers la Base Adresse Locale nouvellement créée afin d'éviter le blocage des liens depuis certaines boites mails.

Mise à jour liée au changement du nom de domaine

---

lib/emails/__tests__/bal-creation-notification.js

2 tests unitaires échouaient lors de la vérification

Fix des tests échoués

---

lib/models/__tests__/base-locale.mongo.js
lib/models/base-locale.js
lib/routes/__tests__/base-locale.js
lib/routes/index.js

- En cas de recherche d'un département inexistant, renvoie :  
```json 
{"code": 404, "message": "Le département :codeDepartement n’existe pas"}
```
- Renvoi d'un tableau vide si aucune Base Locale n'est trouvée
- Ajout des tests liés aux changements des méthodes utilisées
- Modification de la route : 
- Avant -> `/stats/departement/:codeDepartement`
- Après ->  `/stats/departements/:codeDepartement`

Amélioration de la gestion des réponses lors d'une recherche par département

---

lib/emails/__tests__/recovery-notification.js
lib/emails/recovery-notification.js
lib/models/base-locale.js
lib/routes/index.js

Création d'une nouvelle route permettant l'envoi d'un mail contenant un lien d'administration pour toutes les Bases Adresses Locales associées à une adresse email.
`[POST] /bases-locales/recovery`
**body**
```
{email: 'user@mail.fr'}
```
---

Envoi d'un email de récupération des BAL d'un utilisateur

---

lib/models/__tests__/base-locale.mongo.js
lib/models/__tests__/base-locale.schema.js
lib/models/base-locale.js
lib/routes/__tests__/base-locale.js

- Le champ `nom` est requis lors de la création d'une BAL
- Ajout des tests liées au nouveau modèle

Obligation de renseigner "nom" lors de la création d'une BAL

---

lib/models/__tests__/numero.mongo.js
lib/models/__tests__/numero.schema.js
lib/models/numero.js

Le traitement appliquer à la chaine de caractère du suffixe avait pour effet d'attribuer une valeur par défaut (`null`) à ce champ même quand celui-ci n'était pas présent dans le `payload`. Ce qui avait comme effet de bord d'écraser le `suffixe` si celui-ci existait.

Modifications de la gestion des suffixes

---

lib/models/numero.js
lib/routes/__tests__/numeros.js
lib/routes/index.js

- la route `/toponymes/:toponymeId/numeros` renvoie la liste des numéros avec un objet voie au lieu d'un "array"
- renvoie également un format étendu des numéros avec l'ajout de `Numero.expandModel(numero)`
- mise à jour des tests liés à la méthode
*edit : 04/05*
- ### ~~liée à la [PR #329](https://github.com/etalab/editeur-bal/pull/329) de `editeur-bal`~~
- `$lookup` est remplacé par deux appels à la base de données mongo
- ### liée à la [PR #333](https://github.com/etalab/editeur-bal/pull/333) de `editeur-bal`
*edit : 05/05*
- `for of` remplacé par `map`
- utilisation d'un identifiant de voie unique

Amélioration de la méthode fetchByToponyme et de la route y faisant référence

---

lib/models/__tests__/numero.mongo.js
lib/models/numero.js

Il est apparu que certaine BAL étaient corrompu car certain numéro n'avaient plus de voie associé.
Cette PR empêche la mise à jour d'un numéro avec une voie ayant pour valeur `null`.

Empêcher la mise à jour d'un numéro avec une voie nulle

---

lib/export/__tests__/csv-bal.js
lib/export/__tests__/geojson.js
lib/export/csv-bal.js
lib/export/geojson.js
lib/models/__tests__/base-locale.mongo.js
lib/models/__tests__/numero.mongo.js
lib/models/__tests__/numero.schema.js
lib/models/__tests__/toponyme.mongo.js
lib/models/__tests__/toponyme.schema.js
lib/models/base-locale.js
lib/models/numero.js
lib/models/toponyme.js
lib/populate/__tests__/extract-csv.js
lib/populate/extract-csv.js
lib/routes/__tests__/base-locale.js
lib/routes/__tests__/numeros.js
lib/routes/__tests__/toponymes.js
lib/routes/index.js
migrations/2021-05-20-parcelles.js

Cette PR a pour objectif de permettre l'attribution de parcelles cadastre à des numéros ou toponymes. Ce champ vise à compléter le format BAL 1.2 en permettant l'alimentation de `cad_parcelles`.
- Ajout d'un champ `parcelles` sur les `Numero`
- Ajout d'un champ `parcelles` sur les `Toponyme`
- Export du champ `parcelles` dans le geojson
- Import/export du champ `cad_parcelles` dans le le format `CSV`
- Ajout et mise à jour des tests pour la gestion des parcelles.
- Ajout du champ `parcelles: []` à tous les `Numero` et `Toponyme`.
----
Cette PR est liée à [editeur#347](https://github.com/etalab/editeur-bal/pull/347)

Ajout des parcelles dans les numéros

---

lib/models/__tests__/numero.mongo.js
lib/models/numero.js

Lors de l'importation de plusieurs numéros, aucun argument n'était passé à numéro concernant les parcelles, ce qui entrainait un bug dans la partie front de l'application.
Cette PR ajoute une valeur par défaut à `numero.parcelles` lors de l'import multiple, pour correspondre au reste.
Par défaut, `numero.parcelles = []`

Correction de la valeur par défaut de numero.parcelles

---

lib/emails/__tests__/recovery-notification.js
lib/emails/recovery-notification.js
lib/models/base-locale.js
lib/routes/index.js

Il n'est pour le moment possible que de faire une demande de récupération de token sur la totalité des BAL liées à une adresse email. Hors offrir la possibilité de faire cette demande sur une BAL spécifique pourrait permettre aux utilisateurs de retrouver et reprendre leur adressage sur une BAL indiqué par l'alerte de création.
Cette PR viendrait donc offrir une solution de résolution à [Ajout de la suppression dans l'alerte "BAL déjà existantes"](https://github.com/etalab/editeur-bal/pull/365)
- Ajoute de la propriété `id` attendu par la route `/bases-locales/recovery`
- Modification du contenu du mail récupération afin de démarquer l'envoi de la liste des BAL liées à l'adresse email de la l'envoi d'un BAL en particulier

Demande de récupération de token pour une BAL en particulier

---

lib/export/__tests__/csv-bal.js

Modification des tests d'exportation d’une Base Adresse Locale en CSV pour prendre en compte la valeur `0` sur le champ `numero`.
Fix  #242

Modification du test d’exportation CSV

---

lib/models/numero.js
lib/routes/__tests__/numeros.js
lib/routes/index.js

Cette PR propose de masquer les commentaires des numéros en mode consultation.
Les routes `/voie/id_voie/numeros` , `/toponymes/id_toponyme/numeros` et `/numeros/numero_id` attendent désormais un jeton d'authentification.
Si aucun jeton n'est envoyé, elles retournent un numéro sans commentaire.
- GET `/voie/id_voie/numeros`
- GET `/toponymes/id_toponyme/numeros`
- GET `/numeros/numero_id`
_Cette modification fait suite à l'issue [#394](https://github.com/etalab/editeur-bal/issues/394) de l'[editeur-bal](https://github.com/etalab/editeur-bal)._
---
- Ajout de la fonction `filterSensitiveFields` au modèle `Numero`
- Modification des routes pour prendre en compte le jeton d'authentification.
- Ajout de tests pour vérifier la présence ou non des commentaires.

Masque les commentaires en mode consultation

---

lib/emails/__tests__/bal-publication-notification.js
lib/emails/__tests__/new-admin-notification.js
lib/emails/__tests__/token-renewal-notification.js
lib/emails/bal-publication-notification.js
lib/emails/new-admin-notification.js
lib/emails/token-renewal-notification.js

Lorsqu'un utilisateur ajoute un administrateur à sa Base Adresse Locale, le courriel reçu contient un bouton qui permet d'ouvrir l'éditeur en incluant le jeton d'administration.
Certains utilisateurs, généralement ceux qui utilisent un logiciel de mail spécifique ou ne respectant pas les standards, ne peuvent pas utiliser ce bouton.
Cette PR ajoute un lien, en plus du bouton, pour permettre à l'utilisateur de copier / coller le lien directement dans son navigateur.
Après discussion, nous avons décidé d'ajouter ce lien dans tous les courriels concernés : 
- Courriel de publication d'une Base Adresse Locale
- Courriel de renouvellement de jeton
- Courriel d'ajout d'un administrateur
- Correction de la balise <title /> de certain mail

Ajout d'un liens bruts pour faciliter l'administration des Bases Adresses Locales par courriel

---

lib/routes/__tests__/base-locale.js
lib/routes/index.js

Restreint les appels permettant d'ajouter et supprimer une commune d'une BAL pour :
- interdire la suppression de la dernière commune d'une BAL
- interdire l'ajout d'une nouvelle commune à une BAL qui en a déjà une
Mes-Adresses est déjà conforme à ces changements.

Verrouillage mono-commune

---

lib/models/base-locale.js
lib/populate/__tests__/extract-csv.js
lib/populate/extract-csv.js
lib/routes/index.js

Avec cette PR, la création de BAL contenant plusieurs communes ne sera plus possible lors du téléversement d'un fichier csv
- La route `/bases-locales/:baseLocaleId/upload` devient `/bases-locales/:baseLocaleId/communes/:codeCommune/upload`
- Ajout de l'argument `codeCommune` à la méthode `BaseLocale.importFile`
- Modification de la méthode `extractFromCsv` afin qu'elle ne prenne en compte qu'une commune
- Mise à jour du test `extract-bal`

Limitation à une commune lors du téléversement d'un fichier csv

---

lib/models/__tests__/base-locale.mongo.js
lib/populate/__tests__/extract-ban.js
lib/populate/extract-ban.js
lib/routes/__tests__/base-locale.js

Règles supprimées :
- lorsque le nom de la voie n'est pas présent (impossible)
- lorsque le numéro est invalide ou 0 ou >5000 (impossible ou plus problématique à ce jour de par le fonctionnement de la BAN)

Suppression de règles de filtration obsolètes à l'import BAN

---

lib/export/csv-bal.js
lib/models/base-locale.js
lib/populate/extract-csv.js
lib/routes/__tests__/base-locale.js
lib/routes/stats.js
lib/util/cog.js
lib/util/contours-communes.js
package.json
yarn.lock

Cette PR a pour objectif de passer au COG 2022.
La migration des données a été réalisée à la main, et ne concernait qu'une seule commune.
En résumé :
- Mise à jour de `@etalab/bal` (et adaptation du code lié au passage à la version `2.x`
- Mise à jour du lien de téléchargement des contours administratifs
- Mise à jour de `@etalab/decoupage-administratif` (`2.0.0`)

Passage au COG 2022

---

lib/emails/__tests__/bal-publication-notification.js
lib/emails/bal-publication-notification.js

Le titre `Ne vous arrêtez pas en si bon chemin !` devient `Continuez l’édition de cette Base Adresse Locale` afin d'apporter de la clarté pour les communes qui justement n'ont pas édité leur BAL.

Modification d'un titre dans la notification de publication

---

lib/sync/index.js
package.json

Corrige une anomalie majeure dans la fonction `updateConflictStatus` dont le premier appel MongoDB retournait un curseur.
Désormais on retourne un tableau et on gère toutes les BAL retournées.
En supplément, l'exécution en parallèle des items de la boucle detectConflict est plafonnée à 10 pour éviter les goulets d'étranglement sur les machines lentes.
Lié à #318 mais ne suffit probablement pas à fermer l'issue.

Correction de la procédure de détection des conflits

---

.env.sample
lib/models/base-locale.js
lib/populate/extract-ban.js
lib/sync/api-depot.js
lib/util/api-ban.js

Actuellement, seules les Bases Adresses Locales publiées via Mes Adresses sont affichées sur le tableau de bord. Cette PR propose d'ajouter les également les BAL publiées en dehors de l'outil dans les statistiques envoyées au tableau de bord.

Ajoute les BAL publiées en dehors de Mes Adresses aux statistiques du dashboard

---

lib/sync/api-depot.js

Lorsqu'une tentative publication d'une BAL échoue, car celle-ci n'est pas valide, une erreur `500` accompagnée du message `La fichier BAL n’est pas valide. Merci de contacter le support.` est renvoyée.
Cependant, notre système de gestion des erreurs attribue automatiquement le message `Une erreur inattendue est survenue.` aux erreurs 500 afin de ne pas exposé des messages illisibles pour les utilisateurs.
Cette PR propose de modifier le code `500` en `417` `Expectation failed`.

Modification du code erreur lorsqu'une BAL n'est pas valide lors de la publication

---

package.json
yarn.lock

Mise à jour de la dépendance `@etalab/bal` de la `v2.3.3` à la `v2.4.0`.
[Release v2.4.0](https://github.com/BaseAdresseNationale/bal/releases/tag/v2.4.0)

Mise à jour @etalab/bal en v2.4.0

---

lib/models/base-locale.js
lib/models/numero.js
lib/models/toponyme.js
lib/models/voie.js

Il est apparu que les schémas de validation de l'API pouvaient être différents de ceux demandés par le format BAL.
Cette PR corrige :
- le nombre de caractères minimal du nom d'une voie à 3
- le nombre de caractères maximum du suffixe d'un numéro à 9
Corrige [Mes Adresses #562](https://github.com/BaseAdresseNationale/mes-adresses/issues/562) et [Mes Adresses #492](https://github.com/BaseAdresseNationale/mes-adresses/issues/492)

Corrige les schemas de validation 

---

lib/models/__tests__/base-locale.schema.js
lib/models/__tests__/numero.schema.js
lib/models/__tests__/toponyme.schema.js
lib/models/base-locale.js
lib/models/numero.js
lib/models/toponyme.js
lib/models/voie.js

Les schémas de validation des différents modèles (base-locale, voie, toponyme, numéro, etc) renvois actuellement des messages d'erreur prédéfinis et en anglais.
Afin de garder une interface entièrement en français, ces messages ne sont pas affichés dans l'éditeur et prive l'utilisateur de comprendre une erreur de validation quand celle-ci arrive.
Lorsqu'ils correspondent à une erreur que peut faire l'utilisateur depuis un formulaire, alors les messages d'erreur on était remplacés par de nouveaux messages en français.
De plus, si ces erreurs correspondent à une validation du format BAL, alors c'est l'erreur du Validateur BAL qui est renvoyée.
Ces messages ont pour objectif de pouvoir être afficher dans les différents formulaires de l'éditeur.
**Exemple**:

Remplace les messages de validation Joi par ceux du Validateur BAL

---

package.json
yarn.lock

Mise à jour de got de `v11.8.3` à `v11.8.5`

Mise à jour de got en v11.8.5

---

lib/cadastre.js
lib/com.js
lib/routes/__tests__/commune.js
lib/routes/index.js
lib/util/__tests__/cadastre.js
lib/util/__tests__/com.js

Cette PR propose d’ajouter la propriété `isCom` à la route `/commune` .
Cette propriété permet d’identifier si la commune fait partie des [Collectivités d’Outre-Mer](https://fr.wikipedia.org/wiki/Collectivit%C3%A9_d%27outre-mer).
La route `/commune/{codeCommune}` renverra donc un objet : 
```json
{
"hasCadastre": false,
"isCom": true
}
```
- Ajout de la fonction isCOM
- Ajout de la fonction isCOM à la route `/commune` 
- Mise à jour des tests

Ajoute la propriété `isCom` à la route commune

---

lib/populate/extract-ban.js

Certaines communes, les Collectivités d’Outre-Mer notamment, ne disposent d'aucune adresse pouvant être extraite depuis l'API de dépôt ou de Base Adresse Nationale.
Pour ces communes, il n'est pas possible d'utiliser la fonctionnalité `populate` permettant d'initialiser une Base Adresse Locale avec des adresses déjà connues. 
Ce cas n'est actuellement pas géré et provoque une erreur.
Cette PR propose de résoudre simplement le cas où aucune adresse n'est trouvée en renvoyant `{voies: [], numeros: [], toponymes: []}` comme valeur par défaut.

Gestion des communes sans adresse connue

---

com-maps-styles.json
lib/com.js
lib/routes/__tests__/commune.js
lib/routes/index.js
lib/util/__tests__/com.js

- Ajout de la liste des disponibilités des styles de carte => `com-maps-styles.json`
- Ajout de la fonction `checkHasMapsStyles` dans `lib/com`
- Mise à jour des tests
- La route `/commune/:codeCommune` retourne :
```
{
"hasCadastre": boolean,
"isCOM": boolean,
"hasOpenMapTiles": boolean,
"hasOrtho": boolean,
"hasPlanIGN": boolean
}
```
----

Vérifie la présence des styles de cartes

---

lib/models/base-locale.js
lib/models/voie.js

En lien avec issue #333 : 
J'ai remplacé le count() par countDocuments, il me semblait plus judicieux d'utiliser countDocuments qu'estimateDocumentCount.
Il y avait d'autres syntaxes avec le find : mongo.db.collection('numeros').find({voie: mongo.parseObjectID(id)}).count()
Je ne savais pas trop si ca concernait aussi ces cas la, si oui je ferai les modifications.

Modif count() par countDocuments

---

lib/models/__tests__/numero.schema.js
lib/models/numero.js
lib/models/voie.js
lib/populate/extract-csv.js
package.json
yarn.lock

@etalab/bal : `2.4.0` -> `2.7.1`
⚠️ @etalab/bal devient `@ban-team/validateur-bal`

Mise à jour du validateur bal

---

lib/export/__tests__/csv-bal.js
lib/export/csv-bal.js
lib/populate/__tests__/extract-csv.js
lib/populate/extract-csv.js
package.json
yarn.lock

Cette PR propose d’ajouter la gestion des langues régionales lors de l’importation ou de l’exportation d’une Base Adresse Locale au format CSV.
- Prise en compte du champ `nomAlt` à l’exportation et importation d’une BAL en CSV
- Création d’une fonction pour créer le `header` du fichier CSV
- Mise à jour du validateur
- Mise à jour des tests

Ajout des langues régionales dans l’importation / exportation au format CSV

---

lib/models/__tests__/toponyme.mongo.js
lib/models/__tests__/voie.mongo.js
lib/models/nom-alt.js
lib/models/toponyme.js
lib/models/voie.js

resolves #348 
- Ajout de la méthode `cleanNomAlt` aux modèles `voie` et `toponyme`

Supprime les espaces superflus pour les langues régionales

---

lib/populate/extract-csv.js
lib/util/__tests__/string.js
lib/util/string.js
migrations/2021-04-20-new-toponyme.js
package.json
yarn.lock

Resolves #353 
- Ajout de la dépendance [@etalab/adresses-util](https://github.com/BaseAdresseNationale/adresses-util)
- Création de 2 fonctions `beautifyUppercased` (pour la propriété `nom`) et `beautifyNomAlt` (pour `nomAlt`)
- Utilisation des fonctions d'amélioration dans `lib/populate/extract-csv`
*edit 05/08*
**Bug à corriger :**
L'utilisation de `beautifyUppercased` rend inopérant l'accès aux voies (`voiesIndex[voieString]`) et aux toponymes (`toponymesIndex[toponymeString]`) lors du parsing du csv.
En effet, `toponymesIndex` et `voiesIndex` utilisent la fonction `normalizeString` sur la propriété `nom`, des voies formatées par `beautifyUppercased`.
Tandis que `voieString` et `toponymeString` utilisent également la fonction `normalizeString`, mais sur un élément non formaté du csv. …

Amélioration des libellés des voies et des toponymes en majuscule lors de l'import

---

lib/models/__tests__/base-locale.mongo.js
lib/models/base-locale.js
lib/sync/index.js

Il semblerait qu'un certain nombre d'utilisateurs publie des BAL sans adresses lorsqu'ils commencent leur adressage. 
Cette PR empêche le change de status à `ready-to-publish` ou `published` si la BAL n'a aucune adresse.

Empêcher la publication de BAL sans adresse

---

lib/models/__tests__/base-locale.mongo.js
lib/models/__tests__/base-locale.schema.js
lib/models/__tests__/nom-alt.schema.js
lib/models/__tests__/numero.mongo.js
lib/models/__tests__/numero.schema.js
lib/models/__tests__/position.schema.js
lib/models/__tests__/toponyme.mongo.js
lib/models/__tests__/toponyme.schema.js
lib/models/__tests__/voie.mongo.js
lib/models/__tests__/voie.schema.js
lib/models/base-locale.js
lib/models/nom-alt.js
lib/models/numero.js
lib/models/position.js
lib/models/toponyme.js
lib/models/voie.js
lib/routes/__tests__/base-locale.js
lib/routes/__tests__/numeros.js
lib/routes/__tests__/toponymes.js
lib/routes/__tests__/voies.js
lib/util/__tests__/payload.js
lib/util/__tests__/validateur-bal.js
lib/util/payload.js
lib/validateur-bal.js
package.json
yarn.lock

Actuellement la validation des modèles est effectuée avec [joi](https://joi.dev). 
Cependant, la majorité des vérifications consiste à imiter le travaille que fait le [validateur-bal](https://github.com/BaseAdresseNationale/validateur-bal) afin que les BAL soient conformes au format.
Des différences de validation ont fini par voir le jour entre Mes Adresses et le Validateur, empêchant la publication de certaines BAL (ex : voie de moins de 3 caractères).
Cette PR propose de remplacer le `Joi` par une validation faite maison aidée par le `validateur-bal`. 
Les modèles de données seront donc toujours en accord avec la dernière version du `validateur-bal`. Et les messages d'erreur étant aussi ceux du validateur-bal, ils peuvent être directement renvoyés à l'utilisateur.
De plus, ne plus …

Validation des schémas de données grâce au validateur-bal

---

lib/export/geojson.js
lib/populate/extract-csv.js
lib/util/string.js
migrations/2021-04-20-new-toponyme.js
package.json
yarn.lock

~~## ⚠️ Ne pas merger avant [cette PR](https://github.com/BaseAdresseNationale/adresses-util/pull/15) ⚠️~~
Cette PR propose d’ajouter une fonction `getBestPosition` permettant de modifier l’ordre d’affichage des positions.
Jusqu’à présent, l’ordre des positions était choisi en fonction de l’ordre des positions et non du type.
Avec cette modification, l’ordre sera défini grâce à un algorithme renvoyant la position prioritaire. 
_**Les tests ne pourront fonctionner que lorsque `adresses-util` sera mis à jour, cf [cette PR](https://github.com/BaseAdresseNationale/adresses-util/pull/15)**_ -> OK !
Fix [#591 mes-adresses](https://github.com/BaseAdresseNationale/mes-adresses/issues/591)

Renvoi la position prioritaire en fonction de son type

---

lib/emails/__tests__/recovery-notification.js
lib/emails/recovery-notification.js
lib/emails/util.js
lib/models/__tests__/base-locale.mongo.js
lib/models/base-locale.js
lib/routes/__tests__/base-locale.js
lib/routes/index.js

Resolves #341 
- Création de `getApiRecoveryUrl`
- Modification du template de l'e-mail de récupération des BAL
- Ajout de la route `/bases-locales/:baseLocaleId/:token/recovery` (GET)

Intègre la récupération des BAL "supprimées"

---

server.js

Aucun log n'est actuellement affiché en console au démarrage du serveur. Or la préparation des contours des communes peut prendre un certain temps.
Affiche deux logs console:
- Début de la préparation des contours des communes
- Quand le serveur est prêt et indique sur quel port

Ajout de logs au démarrage du serveur

---

lib/models/__tests__/toponyme.schema.js
lib/models/toponyme.js
lib/routes/__tests__/toponymes.js

Seulement deux règles de validation sont appliquées aux noms des toponymes :
- Avoir plus d'un caractère
- Avoir moins de 200 caractères
Cependant, un certain nombre de toponymes avec des noms incorrecte remonte dans le support.
Le nom du toponyme est validé par le `validateur-bal` en utilisant le champ `voie_nom` qui utilise les mêmes critères de validation.
L'erreur renvoyée par le validateur est en revanche modifiée pour ne pas dire "_xxx de la voie_" mais bien "_xxx du toponyme".
Fix [BaseAdresseNationale/mes-adresses/721](https://github.com/BaseAdresseNationale/mes-adresses/issues/712)

Valide le nom des toponymes avec le validateur BAL

---

lib/models/__tests__/base-locale.mongo.js
lib/models/base-locale.js
lib/routes/__tests__/base-locale.js
lib/routes/index.js
lib/util/mongo.js

La route `GET /bases-locales/search` ne permet de récupérer que les bases locales correspondant à un couple email et code commune. Or cette route pourrait accepter d'autre filtre et proposer une réponse paginée afin d'alléger certaine page comme `/all`.
Cette PR propose de renvoyer une réponse paginée sur `GET /bases-locales/search` et ajoute de nouveau filtre à la recherche.
Le nombre de réponses est limité à 20 par défaut.
~- `nom` : Recherche textuelle dans le nom de la base locale. Ce filtre a nécessité la création d'un index sur le champ `nom` des bases locales.~
- `deleted` : Valeur `0` ou `1`. Si `1` seule les bases locales supprimées sont renvoyées. Si `0` seules les bases locales non supprimées sont renvoyées.
- `email` : Recherche de l'email fourni dans les listes des emails de …

Modification majeure de la route /bases-locales/search

---

package.json
yarn.lock

Mise à jour de la dépendance `@etalab/decoupage-administratif` de la `v2.0.0` à la `v2.3.1`.
Cette mise à jour permet notamment le support COM pour les départements et régions.

Mise à jour de @etalab/decoupage-administratif

---

cron.js
lib/models/__tests__/base-locale.mongo.js
lib/models/base-locale.js

L'interface avertie lors de la création d'une BAL de démonstration que celle-ci ne sera disponible que 24. En réalité, ces dernières ne sont jamais supprimées.
Cette PR ajoute une tâche au `cron` qui supprime tous les jours les BAL de démonstration créées il y a plus d'un mois.
Nous gardons encore une belle marge afin de permettre à un utilisateur de convertir sa BAL de démo en brouillon.

Suppression automatisé des BAL de démonstration créées il y a plus d'un mois

---

lib/models/base-locale.js

Une erreur 500 est provoquée lorsque aucun document mongo n'était fourni lors d'un `insertMany`.
De plus, en cas d'erreur, la nouvelle base locale n'était pas supprimée.

Correction de la méthode de fusion de communes

---

lib/util/contours-communes.js
package.json
yarn.lock

Mise à jour de `@etalab/decoupage-administratif v3.0.0` pour la mise à jour du COG 2023.

Mise à jour COG 2023

---

lib/models/base-locale.js

Lors de la création d'une BAL, une erreur est provoquée si jamais une adresse email est invalide est envoyé à l'API.
Cette erreur est provoquée car la fonction `validEmail` est appelé sans fournir d'objet `error`. Cette méthode est ici détournée de sa fonction d'origine qui est de valider le `payload`.
Création d'une fonction `checkValidEmail` qui renvoi uniquement `true/false` et qui pourra être appelé par `validEmails` et  `parseQueryFilters`.
> Des commentaires ont étaient ajoutés afin d'explicité la regex très complexe.

Correction de la vérification de l'adresse email d'une BAL

---

.env.sample
.github/workflows/node.js.yml
.gitignore
README.md
lib/util/contours-communes.js
package.json
scripts/update-contours-communes.js
server.js

La fonction `prepareContoursCommunes` au lancement du serveur peut prendre jusqu'a 30s, car elle charge un geojson je 6000000 de lignes.
Charger les contoures de communes avec le `scripts/update-contours-communes.js` qui va écrire le geosjon dans le fichier `contours-communes.json` à la racine. Peut être appelé via `yarn update-contours`. Le script est également appelé au démarrage de l'appli si je fichier n'existe pas.

Ajouter un script pour charger les contoures des communes

---

lib/models/__tests__/base-locale.mongo.js
lib/models/__tests__/numero.mongo.js
lib/models/__tests__/toponyme.mongo.js
lib/models/__tests__/voie.mongo.js
lib/models/base-locale.js
lib/models/numero.js
lib/models/toponyme.js
lib/models/voie.js
lib/routes/__tests__/numeros.js
lib/routes/__tests__/toponymes.js
lib/routes/__tests__/voies.js
lib/routes/index.js
lib/sync/index.js
lib/util/models.js
lib/util/mongo.js

https://github.com/BaseAdresseNationale/mes-adresses/issues/528
https://github.com/BaseAdresseNationale/mes-adresses/issues/529
https://github.com/BaseAdresseNationale/mes-adresses/issues/772
Ajout du champ `_delete` aux collections `numero`, `voie` et `toponyme`
- `update`: `numeroCount` ne retourne que le nombre de `numero` non archivés
- `exportAsCsv`:  export juste les `numero`, `voie` et `toponyme` non archivés
- `streamToGeoJSON`: renvoie un geojson des `numero`, `voie` et `toponyme` non archivés
- `publishedBasesLocalesStats`: renvoie les nombres de `numero`, `voie` et `toponyme` non archivés
- `getAssignedParcelles`: renvoie les parcelles des `numero` et `toponyme` non archivés
- `batchUpdateNumeros`: ne certifie que les `numero` non archivés
- Route GET …

Ajout de l'archivage/restauration des voies/toponymes/numeros

---

.gitignore
lib/export/__tests__/geojson.js
lib/export/geojson.js
lib/models/__tests__/numero.mongo.js
lib/models/__tests__/voie.mongo.js
lib/models/base-locale.js
lib/models/numero.js
lib/models/voie.js
lib/routes/__tests__/base-locale.js
lib/routes/__tests__/numeros.js
lib/routes/__tests__/voies.js
lib/routes/index.js
lib/sync/api-depot.js
lib/util/__tests__/model.js
lib/util/__tests__/tiles.js
lib/util/models.js
lib/util/mongo.js
lib/util/tiles.js
migrations/2023-06-16-add-tile.js
package.json
yarn.lock

##Context
https://github.com/BaseAdresseNationale/mes-adresses/issues/520
- Ajout de la route `/bases-locales/:baseLocaleId/tiles/:z/:x/:y.pbf` qui renvoit une source de vectoriel tuilé avec trois layers: `voies`, `voies-traces` et `numeros`
- Ajout du champ `tiles` sur les `numeros` et des champs `centroid`, `centroidTiles` et `traceTiles` au `voies`, pour accélérer la recherche mongo lors d'une demande de tuile. C'est sont mise a jour au niveau des models de `voies`
et `numeros`
- Changement des fonction `/export/geojson.js` pour renvoyé les nouveau geojson demandé
- Ajout du champ `bbox` aux `voies` et `toponyme`, auto-généré lors des `GET` de ces dernier
- Suppression de tout le code relatif a l'ancienne route `/bases-locales/:baseLocaleId/geojson`

Remplacer GeoJson par Tuiles Vectorielle

---

lib/routes/index.js

Comme la route /couverture-tiles/:z/:x/:y.pbf contient toutes les geojson de toute les communes de france et qu'il y a plusieurs instance de mes-adresses-api en prod, cela fait exploser la RAM
Exemple après connection a la page https://mes-adresses.data.gouv.fr//dashboard
Désactivation de la route /couverture-tiles/:z/:x/:y.pbf avant fix final

disabled page /dashboard

---

lib/routes/index.js

Mes-adresses-api ne renvoie pas de message lors qu'il y a une réponse en erreur 403, du coup cela créer une erreur le toaster de mes-adresses a un bug d'affichage
Ajouter un message pour les réponse 403 sur mes adresses api

Add message in 403 error response

---

lib/models/base-locale.js
lib/routes/stats.js

Le /dashboard sur mes-adresses a été fermé
Il faut migrer la partie déploiement des BAL sur la page deploiement-bal
Ajout de la route `/stats/bals` qui retourne toutes les BALs, on peut filtrer les champs retourné pour optimiser la requète

Add route get all bals

---

lib/routes/stats.js

Pour la page /deploiement-bal de adresse, nous avons besoin d'une route qui nous donne le compte de tous les status des bals de mes-adresse
- Route GET /stats/bals/status
RESPONSE : [
{"status":"published","count":9062},
{"status":"ready-to-publish","count":2909},
{"status":"replaced","count":855},
{"status":"demo","count":1202},
{"status":"draft","count":12458}
]

Add route /stats/bals/status

---

apps/api/src/modules/base_locale/dto/search_base_locale.query.ts
apps/api/src/modules/base_locale/pipe/search_query.pipe.ts

Fix isDelete in boolean to route `bases_locales/search`

Fix route search bal

---

apps/api/src/modules/base_locale/base_locale.service.ts
apps/api/src/modules/numeros/numero.service.ts
apps/api/src/modules/toponyme/toponyme.service.ts
apps/api/src/modules/voie/voie.service.ts
libs/shared/src/modules/publication/publication.service.ts

- Lorsque le le JOB `sync_outdated` run, les BALS qui étaient `outdated` mais dont le `lastUploadedRevisionId` n'était pas la révision courante publiait normalement alors qu'elle devait normalement finir en `Conflict` a cause d'une coquille dans la fusion du sync.
- Remplacement des `returnDocument: after` par `new: true` comme préconisé par la doc mongoose
Cela a surement entrainé des problème de conflit

Fix status conflict in exec publication

---

apps/api/src/lib/utils/is-admin.utils.ts
apps/api/src/modules/base_locale/base_locale.controller.ts
apps/api/src/modules/base_locale/dto/page_base_locale.dto.ts

Les emails ne sont pas affiché dans bal-admin
Ajouté la gestion du super token sur la route `/bases_locales/search` pour retourner les emails

feat: add sensible field in route /search bal to super admin

---

libs/shared/src/modules/api_depot/api_depot.service.ts

En regardant les log datadog je me suis apercu qu'on avait l'erreur ` Mes Adresses Api Out error { code: 404, message: 'L’identifiant de l’habilitation est invalide' }` des milliers de fois par seconde au heure de pointe (exemple en image)
Cette erreurs vient lorsque on appelle la route /habilitations/undefined, ce qui est le cas pour toutes les BAL de mes-adresses qui sont en brouillon par exemple.
Lorsque l'on arrive sur la page principal de mes-adresse, cela lance une requète /habilitation pour chaque bals, pour toutes celle qui sont en brouillons cela lance une /habilitations/undefined et donc le logs d'erreur.
Cela rend les log quasi illisible et plus chers
Afin de ne pas faire des milliers d'appelle inutile par seconde, on fait le GET /habilitations/:habilitationId a l'api-depot …

fix: useless request api-depot

---

apps/api/src/modules/numeros/numero.service.ts
apps/api/src/modules/voie/voie.service.ts
migrations/2024_04_26_fix_update_tiles_voies.ts

Toutes les nouvelles bal créer depuis la migration non pas de `centroid` et ont des `centroidTiles` et `traceTiles` vide.
Du coup on ne voit pas les libellés des voies
https://trello.com/c/k9vmPujV
Correction de la fonction `updateTiles` pour bien calculer les tiles lors d'un importMany (de bal depuis api-depot / ban-plateforme)
Besoin d'une migration pour corriger toutes les voies qui n'ont pas de tiles

fix: import many numeros calc tiles

---

apps/api/src/modules/base_locale/sub_modules/habilitation/dto/send-pin-code.response.dto.ts
apps/api/src/modules/base_locale/sub_modules/habilitation/habilitation.controller.ts
apps/api/src/modules/base_locale/sub_modules/habilitation/habilitation.service.ts
apps/api/test/habilitation.e2e-spec.ts
libs/shared/src/modules/api_depot/api_depot.service.ts

La route `/bases-locales/:baseLocaleId/habilitation/email/send-pin-code` est beaucoup trop complexe et renvoie inutilement un résultat qu'elle réussise ou non
La route renvoie juste le status 200 si elle réussi et une erreur si l'api-depot a un problème

fix: route send code pin

---

libs/shared/src/params/mailer.params.ts

L'application ne démarre pas si il n'y a pas les paramètre SMTP correct.
Ajout du mode dev, pour que l'application marche si SMTP_HOST n'est pas défini

fix: mailer mode dev

---

apps/api/src/modules/base_locale/base_locale.service.ts
apps/api/src/modules/base_locale/pipe/search_query.pipe.ts

Les Bal n'apparaissent pas coté bal-admin
- On enlève le andWhere (des emails) dans la requète search si l'email n'est pas defini dans le DTO
- On remplace `= null` qui n'est pas interprété par typeorm par `IsNull()` (pour le deletedAt)

hotfix: bug search bal

---

apps/api/src/modules/base_locale/base_locale.service.ts
apps/api/src/modules/base_locale/dto/extended_base_locale.dto.ts
apps/api/src/modules/numeros/numero.service.ts
apps/api/test/base_locale.e2e-spec.ts

Lors du chargement de la page d'accueil de mes-adresses cela peut être très lent si il y a beaucoup de BAL a charger.
Cela est du au fait qu'on récupère tous les numéros de chaque BAL pour mapper le nombre de numeros, certifie et commenataire.
On utilise une requète spécifique avec des count pour postgres

fix: query postgres extended bal

---

apps/api/src/api.module.ts
apps/cron/src/cron.module.ts
libs/shared/src/entities/numero.entity.ts
migrations/1726747666619-on_delete_cascade_numeros.ts

On ne pas supprimer une BAL en demo, cela sort l'erreur:
`update or delete on table "bases_locales" violates foreign key constraint "FK_dd823e556d4b255deae92952f03" on table "numeros"`
Ajout de `ON DELETE CASCADE` sur la contraint `FK_dd823e556d4b255deae92952f03`

fix: delete demo bal

---

Procfile
apps/api/src/api.module.ts
apps/cron/src/cron.module.ts
package.json

Les mirgation typeorm ne passe pas sur scalingo, lorsqu'il y a plusieurs instance
Ajouter la migration run dans le postdeploy du Procfile

scalingo: add hook scalingo-postbuild for typeorm migration

---

apps/api/src/lib/utils/csv.utils.ts
apps/api/src/main.ts
apps/api/src/modules/base_locale/sub_modules/habilitation/habilitation.module.ts
apps/api/src/modules/base_locale/sub_modules/habilitation/habilitation.service.ts
apps/api/src/modules/base_locale/sub_modules/populate/populate.module.ts
apps/api/src/modules/base_locale/sub_modules/populate/populate.service.ts
apps/api/test/habilitation.e2e-spec.ts
apps/cron/src/cron.module.ts
apps/cron/src/main.ts
apps/cron/src/task_queue.class.ts
apps/cron/src/tasks/detect_conflict.task.ts
apps/cron/src/tasks/sync_outdated.task.ts
apps/cron/test/task.e2e-spec.ts
libs/shared/src/modules/api_depot/api_depot.module.ts
libs/shared/src/modules/api_depot/api_depot.service.ts
libs/shared/src/modules/ban_plateform/ban_plateform.module.ts
libs/shared/src/modules/ban_plateform/ban_plateform.service.ts
libs/shared/src/modules/logger/logger.service.ts
libs/shared/src/utils/logger.utils.ts
package.json
yarn.lock

Les logs sur datadog sont ilisible car scalingo rajouter un header a chaque ligne.
Installé winston pour sortir les erreur en une seule lignes

log: add winston

---

Procfile
apps/api/src/lib/utils/csv.utils.ts
apps/api/src/modules/numeros/dto/update_batch_numero_change.dto.ts
apps/api/test/base_locale.e2e-spec.ts
apps/api/test/numero.e2e-spec.ts
apps/api/test/publication.e2e-spec.ts
apps/api/test/toponyme.e2e-spec.ts
apps/cron/test/task.e2e-spec.ts
libs/shared/src/entities/position.entity.ts
migrations/1736244568004-delete_position_inconnue.ts
scripts/postdeploy.sh

Le type de position `inconnue` ne passe pas le validateur
Il faut retirer la possibilité d'utiliser le type de position `inconnue` dans l'application mes-adresses
- Mettre type position `entrée` par default a l'import
- Changer l'enum
- Ajouter les validateur de position sur les dto
- Faire une migration de toute les ancienne positions

fix: delete position type inconnue

---

Procfile
apps/api/src/lib/utils/csv.utils.ts
apps/api/src/modules/numeros/dto/update_batch_numero_change.dto.ts
apps/api/test/base_locale.e2e-spec.ts
apps/api/test/numero.e2e-spec.ts
apps/api/test/publication.e2e-spec.ts
apps/api/test/toponyme.e2e-spec.ts
apps/cron/test/task.e2e-spec.ts
libs/shared/src/entities/position.entity.ts
migrations/1736244568004-delete_position_inconnue.ts
scripts/postdeploy.sh

Le type de position `inconnue` ne passe pas le validateur
Il faut retirer la possibilité d'utiliser le type de position `inconnue` dans l'application mes-adresses
- Mettre type position `entrée` par default a l'import
- Changer l'enum
- Ajouter les validateur de position sur les dto
- Faire une migration de toute les ancienne positions

feat: delete position inconnue

---

apps/api/src/lib/utils/csv.utils.ts

Lorsque l'on populate une BAL a partir d'une BAL qui n'a pas les toponyme en 99999, ces dernier son créé avec l'uuid de la voie.

fix: bug toponyme same idBan voie

---

apps/api/test/base_locale.e2e-spec.ts
apps/api/test/stats.e2e-spec.ts
libs/shared/src/entities/base_locale.entity.ts

Ajoute le champ calculé "communeNom" au chargement des entités base locale (pour éviter de faire des call à l'API géo côté front juste pour récupérer le nom de la commune)

feat: add computed communeNom to bal entity
