- lib/models/__tests__/position.schema.js
- lib/models/__tests__/voie.schema.js
- lib/models/position.js
Remplace la `FeatureCollection` par un `Point GeoJSON`
> Corrige le schema Position

- lib/models/__tests__/voie.mongo.js
- lib/models/__tests__/voie.schema.js
- lib/models/voie.js
- lib/routes.js
- `create(idBal, codeCommune, payload)` : Crée une nouvelle Voie.
- `update(id, payload)` : Modifier une Voie.
- `fetchOne(id)` : Renvoi une commune?
- `fetchAll(idBal, codeCommune)` : Renvoi toutes les voies d'une commune.
- `remove(id)` : Supprime une commune.
- `POST` : Créer une voie dans la commune
- `GET` : Lister les voies d'une commune
- `GET` : Retourner les informations concernant une voie
- `PUT` : Modifier une voie
- `DELETE` : Supprimer une voie
> Ajout du modèle Voie et de ses routes

- lib/models/__tests__/numero.mongo.js
- lib/models/numero.js
- lib/routes.js
- `create(idVoie, payload)` : Crée un nouveau Numero.
- `update(id, payload)` : Modifier un Numero.
- `fetchOne(id)` : Renvoi un Numero.
- `fetchAll(idVoie)` : Renvoi toutes les numéros d'une voie.
- `remove(id)` : Supprime un numéro.
`POST` : Créer un numéro dans la voie
`GET` : Lister les numéros de la voie
`GET` : Retourner les informations concernant un numéro
`PUT` : Modifier un numéro
`DELETE` : Supprimer un numéro
> Ajout du modèle Numero et de ses routes

- lib/models/__tests__/numero.mongo.js
- lib/routes.js
- lib/routes/__tests__/base-locale.js
- lib/routes/index.js
- server.js
> Préparation des tests d'API

- lib/models/numero.js
- lib/routes/__tests__/base-locale.js
- lib/routes/__tests__/numeros.js
- lib/routes/__tests__/voies.js
- lib/routes/index.js
Ajout des tests API pour les `BaseLocale`, `Voie` et `Numero`
> Tests unitaires sur l'API CRUD

- lib/models/__tests__/voie.mongo.js
- lib/models/__tests__/voie.schema.js
- lib/models/voie.js
- Remove unique constraint (which wasn't well implemented)
- Add a clean step to remove useless white-spaces
> Update Voie.name save behavior

- lib/models/__tests__/numero.mongo.js
- lib/models/__tests__/voie.mongo.js
- lib/models/numero.js
- lib/models/voie.js
- lib/util/__tests__/base62.js
- lib/util/__tests__/mongo.js
- lib/util/__tests__/payload.js
- lib/util/__tests__/w.js
- lib/util/mongo.js
La modification ou suppression d'un document aura pour effet de mettre à jour le champ `_updated` des documents dont il dépend.
Fix #14 Mise à jour des dates
> Mise à jour en cascade des dates de dernière modification

- lib/export/__tests__/csv-bal.js
- lib/export/csv-bal.js
- lib/models/base-locale.js
- lib/routes/__tests__/base-locale.js
- lib/routes/index.js
- package.json
- yarn.lock
> Export au format CSV BAL/AITF 1.1

- lib/export/__tests__/geojson.js
- lib/export/geojson.js
- lib/models/base-locale.js
- lib/routes/__tests__/base-locale.js
- lib/routes/index.js
- package.json
- yarn.lock
`GET /bases-locales/:id/communes/12345/geojson`
> Export des adresses d'une commune au format GeoJSON (pour affichage)

- lib/models/__tests__/base-locale.mongo.js
- lib/models/__tests__/numero.mongo.js
- lib/models/__tests__/voie.mongo.js
- lib/models/base-locale.js
- lib/models/numero.js
- lib/models/voie.js
- lib/populate/extract-csv.js
- lib/routes/index.js
- package.json
- yarn.lock
`POST /bases-locales/:id/upload`
- Écrase toutes les données existantes
- Nécessite un fichier au format BAL/AITF 1.1
Retourne un objet JSON de la forme suivante :
```js
{
isValid: true || false,
accepted: 100, // Nombre de lignes du fichier acceptées
rejected: 10, // Nombre de lignes du fichier rejetées
communes: ['12345', '23456'], // Liste des communes présentes dans les données importées
voies: 7, // Nombre de voies importées
numeros: 100 // Nombre de numéros importés
}
```
Implément #21
> Import d'une BAL au format CSV

- lib/populate/extract-csv.js
> Return isValid: false when validation throws

- lib/models/__tests__/numero.mongo.js
- lib/models/__tests__/numero.schema.js
- lib/models/numero.js
- package.json
- yarn.lock
> Suffixe insensible à la casse et normalisé en minuscule

- lib/models/__tests__/numero.mongo.js
- lib/models/__tests__/numero.schema.js
- lib/models/numero.js
Permet de modifier la voie attribué à un numéro.
> Ajout de la voie lors de l'édition d'un numéro

- lib/models/numero.js
> Ajout d'un séparateur lorsque le suffixe est un nombre

- .env.sample
- lib/models/__tests__/base-locale.mongo.js
- lib/models/base-locale.js
- lib/routes/__tests__/base-locale.js
- lib/routes/index.js
- lib/util/geo-api.js
- package.json
- yarn.lock
- Ajout de la lib `isomorphic-unfetch`
- Utilisation de l'API `geo.api.gouv.fr` pour récupérer les codes communes d'un département
- Création de la route `/stats/departement/:codeDepartement` qui liste les BAL d'un département en fonction de son code
> Création d'une route listant les BAL en fonction du département

- lib/models/base-locale.js
- lib/routes/__tests__/base-locale.js
- lib/routes/index.js
- lib/util/contours-communes.js
- lib/util/mongo.js
- server.js
- Récupération des contours communes
- Filtrage des contours en fonction des communes présentes dans les BAL
- Création de la route `/stats/couverture-bal`
- Ajout des tests
> Génèrer un GeoJSON de couverture des BAL

- lib/models/__tests__/base-locale.mongo.js
- lib/models/__tests__/base-locale.schema.js
- lib/models/base-locale.js
- lib/routes/__tests__/base-locale.js
- lib/routes/index.js
- lib/util/cog.js
- POST `/bases-locales/create-demo` : Création d'un Base Adresse Locale de démonstration 
```
{
commune: "27115",
populate: true
}
```
```
{
"_id": "XXXXXXXXXX",
"nom": "Base Adresse Locale [DEMO]",
"status": "demo"
"token": 'token',
"communes": ["27115"],
"_updated": "2020-11-23T16:31:35.106Z",
"_created": "2020-11-23T16:31:35.106Z" 
}
```
----
- POST `/bases-locales/:baseLocaleId/transform-to-draft` : Transforme une Base Adresse Locale de démonstration en Base Adresse Locale avec un statut `brouillon`
```
{
"nom": "Base Locale de Breux-sur-Avre",
"email": "email@me.fr"
}
```
```
{
"_id": "XXXXXXXXXX",
"nom": "Base Locale de Breux-sur-Avre",
"status": "draft"
"token": 'token',
"emails": ["email@me.fr"],
"communes": ["27115"],
"_updated": "2020-11-23T16:31:35.106Z",
"_created": …
```
> Meilleure gestion des Bases Adresses Locales de démonstration

- lib/export/__tests__/csv-bal.js
- lib/export/csv-bal.js
Le champ complément de nom de voie est désormais exporté dans le format BAL 1.2.
> Export du complément de nom de voie

- lib/export/__tests__/geojson.js
- lib/export/geojson.js
- lib/models/base-locale.js
- Ajout de la propriété `nomToponyme` à la méthode `numeroVoieToAdresseFeature` 
- Mise à jour des tests
> Ajout de la propriété nomToponyme lors de l'export du geoJSON

- lib/util/mongo.js
- package.json
- yarn.lock
- Passage de `mongodb` 3 à 4
- Passage de `mongodb-memory-server` de 7 à 8
> Mise à jour des bibliothèques MongoDB

- lib/routes/stats.js
- lib/util/cache.js
- Mise en cache du geojson d'une durée de 5 minutes lors de l'appel à la route `/couverture-bal`
> Mise en cache du geojson lié au tableau de bord

- lib/emails/__tests__/bal-publication-notification.js
- lib/emails/bal-publication-notification.js
Ajout texte et ajout bouton redirige vers la page commun
e
> #311: Compléter le mail envoyé à la publication d'une BAL

- lib/habilitations.js
- lib/routes/index.js
- lib/sync/index.js
Dans certains cas une Base Adresse Locale pouvait être en conflit avec elle-même.
L'algorithme de détection n'était pas assez robuste et pouvait souffrir de [*race condition*](https://fr.wikipedia.org/wiki/Situation_de_compétition).
> Correction d'une anomalie sur la détection des conflits

- lib/models/__tests__/nom-alt.schema.js
- lib/models/__tests__/toponyme.mongo.js
- lib/models/__tests__/voie.mongo.js
- lib/routes/__tests__/toponymes.js
- lib/routes/__tests__/voies.js
- package.json
- yarn.lock
Mise à jour de `@ban-team/shared-data` en `v.1.1.0`. Cette mise à jour apport le support du Catalan aux langues régionales.
Ticket principal : BaseAdresseNationale/mes-adresses/pull/651
> Mise à jour de @ban-team/shared-data

- lib/models/__tests__/nom-alt.schema.js
- lib/models/__tests__/toponyme.mongo.js
- lib/models/__tests__/voie.mongo.js
- lib/routes/__tests__/toponymes.js
- lib/routes/__tests__/voies.js
- package.json
- yarn.lock
Reverts BaseAdresseNationale/mes-adresses-api#350
> Revert "Mise à jour de @ban-team/shared-data"

- lib/routes/__tests__/base-locale.js
- lib/routes/__tests__/toponymes.js
- lib/routes/__tests__/voies.js
- lib/routes/index.js
- lib/util/models.js
- Renomme `expandModelWithNumerosCount` => `expandModelWithNumeros`
- Ajout de la propriété `commentedNumeros`
> Extension des modèles. Ajoute les commentaires des adresses

- lib/models/__tests__/base-locale.mongo.js
- lib/models/base-locale.js
- lib/populate/__mocks__/ban.js
- lib/routes/admin.js
Lors de la mise à jour du COG, des communes sont amenées à fusionner. Si une ou plusieurs de ces communes utilisent Mes Adresses afin de gérer leurs BAL, alors nous préparions à la main un fichier CSV issue de la fusion des communes.
Cependant, le fichier BAL ne contient pas toutes les informations "extra" utilisé dans Mes Adresses, comme le tracé des voies ou encore les commentaires.
Création d'une nouvelle méthode `BaseLocale.createBaseLocaleFromCommunesMerge` accessible via une nouvelle route admin `/merge-bases-locales`.
Cette nouvelle méthode a pour objectif de créer une BAL en fusionnant d'autres BAL déjà existante sur Mes Adresses, issue de la BAN ou encore depuis un assemblage des adresses connues de la BAN.
La nouvelle BAL se verra assignée, sans vérification, le code renseigné …
> Nouvelle fonctionnalité de fusion de commune et de BAL

- package.json
- yarn.lock
Changer la version de shared-data, pour ajouter la langue picard
> Ajouter la langue picarde dans Mes Adresses API

- lib/emails/__tests__/token-renewal-notification.js
- lib/emails/token-renewal-notification.js
Fix https://github.com/BaseAdresseNationale/mes-adresses/issues/768
> Correction de la coquille dans le mail de renouvellement du jeton

- package.json
- yarn.lock
https://github.com/BaseAdresseNationale/validateur-bal/issues/76
https://github.com/BaseAdresseNationale/api-depot/issues/89
https://github.com/BaseAdresseNationale/validateur-bal/pull/75
> update validator 2.15.0

- lib/export/__tests__/csv-voies.js
- lib/export/csv-voies.js
- lib/models/base-locale.js
- lib/routes/index.js
https://github.com/BaseAdresseNationale/mes-adresses/issues/137
> Export liste voie csv

- lib/util/mongo.js
Les index de tuiles vectorielle sont mal paramètré sur les `voies`
> correct index tiles voies

- lib/routes/index.js
- lib/util/models.js
A chaque fois qu'on demande un get de d'une bal le expandModel multiplie les appelles x4
Refacto et Opti de la fonction expandModel
> Correct function expand model

- lib/export/geojson.js
- lib/models/base-locale.js
- lib/routes/index.js
PR liée : https://github.com/BaseAdresseNationale/mes-adresses/pull/788
> Ajout du mode daltonien 

- lib/models/base-locale.js
- lib/routes/index.js
- lib/routes/stats.js
La mémoire du serveur est saturée quand on visite la page dashboard mes-adresses. Cette PR supprime la route GET /bases-locales car elle est trop couteuse
> Optimize mes-adresses-api stats routes

- lib/routes/index.js
https://github.com/BaseAdresseNationale/bal-admin/issues/26
> add check token admin

- lib/models/base-locale.js
- regex à revoir pour le match des emails
> fix: email search case insensitive

- .github/workflows/node.js.yml
- package.json
- Ajout du build a la CI
- Ajout du build node 20
- Ajout des contributeur
> ci: improve build node in CI

- apps/api/src/api.module.ts
- apps/api/src/lib/guards/admin.guard.ts
- apps/api/src/modules/admin/admin.controller.ts
- apps/api/src/modules/admin/admin.module.ts
- apps/api/src/modules/admin/admin.service.ts
- apps/api/src/modules/admin/dto/bases_locales_status.dto.ts
- apps/api/src/modules/admin/dto/code_commune.dto.ts
- apps/api/src/modules/admin/dto/fusion_bases_locales.dto.ts
- apps/api/src/modules/base_locale/base_locale.service.ts
- apps/api/src/modules/base_locale/dto/update_base_locale.dto.ts
Création d'une route pour fusionner les BAls
> Feat: route admin fusion communes

- apps/api/src/modules/base_locale/base_locale.controller.ts
- Une commune voit toujours une BAL en conflit supprimée
> feat: query isExist get /bases_loacles

- apps/api/src/modules/numeros/numero.service.ts
Il y avait une error pour certain populate de BAL.
Maintenant les numero avec les numero 0 sont rejeté
> hotfix: populate numero with zero

- apps/api/src/lib/utils/csv.utils.ts
- apps/cron/src/task_queue.class.ts
- apps/cron/src/tasks/detect_conflict.task.ts
- apps/cron/src/tasks/sync_outdated.task.ts
- libs/shared/src/modules/api_depot/api_depot.service.ts
- libs/shared/src/modules/ban_plateform/ban_plateform.service.ts
Actuellement les logs sont ilisible
- Ajout du nom de la fonction qui lance l'error
- console de l'error seul pour être interprété par datadog
> fix: errors logs

- libs/shared/src/validators/validator_bal.validator.ts
- package.json
- yarn.lock
Mettre a jour les package pour les langue régional oc-nicard et oc-prevecal
> feat: add flags for nicard and provencal

- apps/api/src/modules/base_locale/base_locale.controller.ts
- apps/api/src/modules/numeros/numero.controller.ts
- apps/api/src/modules/numeros/numero.service.ts
- apps/api/src/modules/toponyme/toponyme.controller.ts
- apps/api/src/modules/voie/dto/create_voie.dto.ts
- apps/api/src/modules/voie/dto/extended_voie.dto.ts
- apps/api/src/modules/voie/dto/update_voie.dto.ts
- apps/api/src/modules/voie/voie.controller.ts
- apps/api/src/modules/voie/voie.service.ts
- apps/api/test/base_locale.e2e-spec.ts
- libs/shared/src/entities/voie.entity.ts
- libs/shared/src/modules/export_csv/utils/export_csv_bal.utils.ts
- libs/shared/src/utils/filter.utils.ts
- migrations/1732616067459-voie_comment.ts
Ajout du champs `comment` au model `voie`
Ajout le champs `commentaire_voie` à l'export BAL
> feat: add comment to model voie

- apps/api/src/lib/utils/csv.utils.ts
- apps/api/src/modules/toponyme/dto/create_toponyme.dto.ts
- apps/api/src/modules/toponyme/dto/update_toponyme.dto.ts
- apps/api/src/modules/toponyme/toponyme.service.ts
- apps/api/test/base_locale.e2e-spec.ts
- apps/api/test/toponyme.e2e-spec.ts
- libs/shared/src/entities/toponyme.entity.ts
- libs/shared/src/modules/export_csv/utils/export_csv_bal.utils.ts
- migrations/1739867816344-delete_commune-deleguee-from-toponyme.ts
Supprimer la partie `communeDeleguee` des toponymes
https://github.com/BaseAdresseNationale/mes-adresses/pull/988
> fix: delete communeDeleguee from toponyme

- apps/api/src/modules/base_locale/sub_modules/habilitation/dto/send-pin-code.dto.ts
- apps/api/src/modules/base_locale/sub_modules/habilitation/habilitation.controller.ts
- apps/api/src/modules/base_locale/sub_modules/habilitation/habilitation.service.ts
- apps/api/test/habilitation.e2e-spec.ts
- libs/shared/src/modules/api_depot/api_depot.service.ts
Faire la passerelle de l'email pour la route `/habilitation/send-code-pin`
> feat: add email to habilitation route /send-code-pin

- apps/api/src/api.module.ts
- apps/api/src/modules/base_locale/base_locale.controller.ts
- apps/api/src/modules/base_locale/base_locale.module.ts
- apps/api/src/modules/base_locale/base_locale.service.ts
- libs/shared/src/modules/cache/cache.service.ts
- Ajout d'un cache pour stocker lorsque qu'une bal est en populating
- Ajout d'une route pour savoir si une bal est en ppulating
> fix: add route /basesLocales/isPopulating

- apps/api/src/modules/admin/admin.controller.ts
- apps/api/src/modules/admin/admin.module.ts
- apps/api/src/modules/admin/admin.service.ts
- apps/api/src/modules/admin/dto/fusion_bases_locales.dto.ts
- apps/api/src/modules/base_locale/base_locale.service.ts
- libs/shared/src/modules/export_csv/utils/export_csv_bal.utils.ts
Ajout de la route /fusion-communes pour simplifier le passage du COG
> feat: route fusion commune

- .env.sample
- apps/api/src/modules/base_locale/sub_modules/tiles/tiles.controller.ts
- apps/api/src/modules/base_locale/sub_modules/tiles/tiles.module.ts
- apps/api/src/modules/base_locale/sub_modules/tiles/tiles.service.ts
- apps/api/src/modules/numeros/numero.service.ts
- apps/api/src/modules/toponyme/toponyme.controller.ts
- apps/api/src/modules/voie/voie.controller.ts
- apps/api/src/modules/voie/voie.service.ts
- apps/api/test/base_locale.e2e-spec.ts
- apps/api/test/numero.e2e-spec.ts
- apps/api/test/voie.e2e-spec.ts
- libs/shared/src/modules/redis/redis.module.ts
- libs/shared/src/modules/redis/redis.service.ts
- package.json
- yarn.lock
Utilisation de redis pour mettre fichier pbf (des tuiles vectorielle) en cache.
> feat: tiles pbf cache redis
